name: BotAcortadores
on:
  schedule:
    - cron: '*/15 * * * *'  # Esto lo ejecutará 4 veces por hora
  workflow_dispatch:
 # Se ejecuta solo cada 3 horas

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Bot
        run: python bot.py
